clear;clc;
C = imread('lena512.bmp');
M = imread('ctgu256.bmp');
[m, n] = size(M);
M_data = reshape(M, 1, m * n);
C_M = LSB_embed(C, M_data);
M_data_ = LSB_extract(C_M);
M_ = reshape(M_data_(1:m * n), m, n);
figure();
subplot(2, 2, 1);
imshow(C);
title('载体图像');
subplot(2, 2, 2);
imshow(M);
title('秘密信息');
subplot(2, 2, 3);
imshow(C_M);
title('载密图像');
subplot(2, 2, 4);
imshow(M_);
title('提取出的秘密信息');
